# Generated by Django 3.2.7 on 2021-09-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='no_nickname', max_length=20, unique=True),
        ),
    ]
