# Generated by Django 3.2.7 on 2021-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(max_length=100)),
                ('image_uri', models.TextField()),
                ('desc', models.TextField()),
                ('museum_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MainArtifact',
        ),
    ]
