# Generated by Django 3.2.7 on 2021-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image_uri',
            field=models.TextField(),
        ),
    ]
