# Generated by Django 3.2.7 on 2021-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=100)),
                ('artifact_name', models.CharField(max_length=100)),
                ('artifact_size', models.CharField(blank=True, max_length=100)),
                ('artifact_author', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('museum_name', models.CharField(blank=True, max_length=20)),
                ('index_words', models.TextField(blank=True)),
                ('nationality_name', models.CharField(blank=True, max_length=50)),
                ('image_uri', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
